### PR TITLE
make order.put_market (side = bid) behave like other orders..

### PR DESCRIPTION
**Pull request by djpnewton**
..that is the "amount" parameter now refers to the order "stock"

see also issue #32

### CODE REVIEW

**Comment by djpnewton** [comment]
update: fixed market bid order validation and "amount left" calculation

**Comment by haipome** [comment]
This change the current behavior. When use market.put_market bid, the amount of stock can't fixed, because we can't sure the execute price.

**Comment by djpnewton** [comment]
RE: change in behavior, would you prefer an extra parameter to "order.put_market" to set its mode to stock or money (default to money), or a new RPC (eg "order.put_market_stock")

I check the execution price of the order by enumerating the orderbook asks.

**Comment by haipome** [comment]
I would prefer add a new RPC or add an extra optionally param

**Comment by jkmaina** [comment]
Any update on this? Need this feature

**Pull request closed without merging**
